config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  root 'home#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base

  rolify

  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

end

app/models/role.rb
class Role < ActiveRecord::Base

  has_and_belongs_to_many :admins, :join_table => :admins_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if admin_signed_in?
      redirect_to home_dashboard
    else
      redirect_to admin_session_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def alert_class_for(flash_type)
    {:success => 'alert-success', :error => 'alert-danger', :alert => 'alert-warning', :notice => 'alert-info'}[flash_type.to_sym] || flash_type.to_s
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Access</title>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%=root_path%>">Project name</a>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <% unless admin_signed_in? %>
        <ul class="nav navbar-nav navbar-left">
          <li><%= link_to "Iniciar sesión", admin_session_path %></li>
        </ul>
        <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= t('menus.session.options') %> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Cerrar sesión", destroy_admin_session_path, :method => :delete %></li>
            </ul>
          </li>
        </ul>
        <% end %>
      </div>
    </div>
  </nav>

  <div class="container">
    <%= render partial: "shared/flash_messages", flash: flash %>
    <%= yield %>
  </div>

</body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= alert_class_for(type) %> alert-dismissible fade in">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= message %>
  </div>
<% end %>